language: node_js
node_js:
  - 15.3.0
cache:
  directories:
    - node_modules

script:
  - yarn test
  
before_deploy: # 배포전 작업
  - rm -rf node_modules
  - zip -r react-practice *
  - mkdir -p deploy
  - mv react-practice.zip deploy/react-practice.zip
deploy:
  - provider: s3
    bucket: hancup-storage
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: ap-northeast-2 # us-east-1 region이 아니라면 명시해주어야함
    skip_cleanup: true
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: dragonsuperf/react-practice
      branch: master
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: hancup-storage
    key: react-practice.zip
    bundle_type: zip
    application: hancup
    deployment_group: hancup-deploy-gruop
    region: ap-northeast-2 # us-east-1 region이 아니라면 명시해주어야함
    wait-until-deployed: true
    on:
      repo: dragonsuperf/react-practice
      branch: master