language: node_js
node_js:
  - 15.3.0
cache:
  directories:
    - node_modules

script:
  - yarn test
  - yarn build
  
before_deploy: # 배포전 작업
  - zip -r react-practice build
  - mkdir -p deploy
  - mv react-practice.zip deploy/react-practice.zip
deploy:
  - provider: s3
    # rest of S3 deployment for MyApp.zip
    # ⋮
  - provider: codedeploy
    bucket: hancup-storage
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    key: react-practice
    bundle_type: zip
    application: hancup
    deployment_group: hancup-deploy-gruop
    region: ap-northeast-2 # us-east-1 region이 아니라면 명시해주어야함
    wait-until-deployed: true
    edge: true
    on:
      branch: master